rm -rf build
mkdir -p build
cd build
cmake .. -DNNG_STATIC_LIB=ON -DBUILD_SHARED_LIBS=OFF -DNNG_TOOLS=OFF -DNNG_TESTS=OFF -DNNG_ENABLE_TLS=ON\
	-DNNG_PROTO_BUS0=OFF -DNNG_PROTO_PAIR0=OFF -DNNG_PROTO_PAIR1=OFF -DNNG_PROTO_SUB0=OFF -DNNG_PROTO_PUSH0=OFF\
	-DNNG_PROTO_RESPONDENT0=OFF -DNNG_PROTO_PULL0=OFF -DNNG_PROTO_SURVEYOR0=OFF -DNNG_TRANSPORT_TCP=OFF\
	-DNNG_TRANSPORT_ZEROTIER=OFF -DNNG_NUM_TASKQ_THREADS=5 \
	-DMBEDTLS_INCLUDE_DIR=../mbedtls/include -DMBEDTLS_TLS_LIBRARY=../mbedtls/library -DMBEDTLS_X509_LIBRARY=../mbedtls/library -DMBEDTLS_CRYPTO_LIBRARY=../mbedtls/library
cmake --build .
